compressionLevel: mixed

# Issue with cross driver link resolution on Windows https://github.com/evanw/esbuild/issues/3131
# When resolved, enableGlobalCache can be set to true
enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

yarnPath: .yarn/releases/yarn-4.5.2.cjs
