compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
